version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: API-Travels
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    container_name: adminer
    restart: on-failure
    ports:
      - 8080:8080
